#!/usr/bin/env python3
"""Rasterise a TTF into an Adafruit-GFX `GFXfont` header for Arduino_GFX.

Arduino_GFX draws a custom-font glyph at (cursor_x + xOffset, cursor_y + yOffset),
i.e. the cursor Y is the *baseline*, exactly like Adafruit_GFX. Its clipping test,
however, assumes the line box starts at `y - yAdvance*2/3`, so yAdvance must be at
least 1.5x the ascent or tall glyphs get clipped away. That is the only quirk this
generator has to respect.

Glyph bitmaps are a continuous MSB-first bit stream of width*height bits per glyph,
with no row padding -- again matching Adafruit_GFX.

Usage:
    python3 tools/gen_font.py <font.ttf> <pixel-size> <CIdentifier> <out.h>
"""

import math
import sys

from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 0x20, 0xFF  # Latin-1: covers accented artist names
THRESHOLD = 96  # keep thin stems that antialiasing would otherwise wash out
PAD = 48


def render(font, ascent, ch):
    """Return (bitmap_rows, w, h, xoff, yoff) for one character."""
    img = Image.new("L", (PAD * 3, PAD * 3), 0)
    ImageDraw.Draw(img).text((PAD, PAD), ch, font=font, fill=255)
    img = img.point(lambda v: 255 if v >= THRESHOLD else 0, mode="1")

    ink = img.getbbox()
    if ink is None:  # whitespace, or a glyph this face does not have
        return None, 0, 0, 0, 0

    x0, y0, x1, y1 = ink
    w, h = x1 - x0, y1 - y0
    px = img.crop(ink).load()
    rows = [[1 if px[x, y] else 0 for x in range(w)] for y in range(h)]
    return rows, w, h, x0 - PAD, (y0 - PAD) - ascent


def main():
    ttf, size, name, out = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4]
    font = ImageFont.truetype(ttf, size)
    ascent, descent = font.getmetrics()

    bitmap = bytearray()
    glyphs = []

    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        rows, w, h, xoff, yoff = (None, 0, 0, 0, 0)
        if not (0x7F <= code <= 0xA0):  # skip C1 controls and NBSP
            rows, w, h, xoff, yoff = render(font, ascent, ch)

        offset = len(bitmap)
        if rows:
            bits, acc, nbits = [], 0, 0
            for row in rows:
                for bit in row:
                    acc = (acc << 1) | bit
                    nbits += 1
                    if nbits == 8:
                        bits.append(acc)
                        acc, nbits = 0, 0
            if nbits:
                bits.append(acc << (8 - nbits))  # pad the final byte on the right
            bitmap.extend(bits)

        advance = int(round(font.getlength(ch))) if code != 0xA0 else int(round(font.getlength(" ")))
        glyphs.append((offset, w, h, advance, xoff, yoff))

    # Arduino_GFX clips against a box starting at y - yAdvance*2/3; keep the ascent inside it.
    y_advance = max(ascent + descent, math.ceil(ascent * 1.5))

    with open(out, "w") as f:
        f.write(f"// Generated by tools/gen_font.py from {ttf.split('/')[-1]} at {size}px.\n")
        f.write("// Do not edit by hand; re-run the generator instead.\n")
        f.write("#pragma once\n\n#include <Arduino_GFX_Library.h>\n\n")

        f.write(f"const uint8_t {name}Bitmaps[] PROGMEM = {{\n   ")
        for i, b in enumerate(bitmap):
            f.write(f" 0x{b:02X},")
            if i % 12 == 11:
                f.write("\n   ")
        f.write("\n};\n\n")

        f.write(f"const GFXglyph {name}Glyphs[] PROGMEM = {{\n")
        for code, (offset, w, h, adv, xo, yo) in zip(range(FIRST, LAST + 1), glyphs):
            f.write(f"    {{ {offset:5d}, {w:3d}, {h:3d}, {adv:3d}, {xo:4d}, {yo:4d} }},"
                    f"  // 0x{code:02X}\n")
        f.write("};\n\n")

        f.write(f"const GFXfont {name} PROGMEM = {{\n")
        f.write(f"    (uint8_t *){name}Bitmaps,\n    (GFXglyph *){name}Glyphs,\n")
        f.write(f"    0x{FIRST:02X}, 0x{LAST:02X}, {y_advance},\n}};\n")

    print(f"{out}: {len(bitmap)} bytes of bitmap, ascent {ascent}, yAdvance {y_advance}")


if __name__ == "__main__":
    main()
